// Generated by Selenium IDE
const { Builder, By, until } = require("selenium-webdriver");
const chrome = require("selenium-webdriver/chrome");

describe("E2E Test", function () {
  this.timeout(30000);
  let driver;
  beforeEach(async function () {
    let options = new chrome.Options();
    options.addArguments("--headless");
    driver = await new Builder()
      .forBrowser("chrome")
      .setChromeOptions(options)
      .build();
    driver.manage().setTimeouts({ implicit: 10000 });
  });
  afterEach(async function () {
    await driver.quit();
  });

  it("Should add a task", async function () {
    await driver.get("http://localhost:3000/");
    await driver.manage().window().setRect({ width: 1510, height: 871 });

    await driver.wait(until.elementLocated(By.css("input")), 10000);
    const input = await driver.findElement(By.css("input"));
    await input.click();
    await input.sendKeys("this is a task");
    await driver.wait(
      until.elementLocated(By.css("button:nth-child(2)")),
      10000
    );
    await driver.findElement(By.css("button:nth-child(2)")).click();
    await driver.wait(
      until.elementLocated(By.css("button:nth-child(3)")),
      10000
    );
    await driver.findElement(By.css("button:nth-child(3)")).click();
    await driver.wait(
      until.elementLocated(By.css("button:nth-child(4)")),
      10000
    );
    await driver.findElement(By.css("button:nth-child(4)")).click();
  });
});
