name: CI/CD for dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: 16
        working-directory: ./backend

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 16
        working-directory: ./frontend

      - name: Install dependencies for Backend
        run: npm install
        working-directory: ./backend

      - name: Install dependencies for Frontend
        run: npm install
        working-directory: ./frontend

      - name: Run Backend Unit Tests
        run: npm test
        working-directory: ./backend

      - name: Run Frontend Unit Tests
        run: npm test
        working-directory: ./frontend

      - name: Merge dev to main
        uses: pascalgn/automerge-action@v0.15.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
