name: worflow main

on:
  workflow_run:
    workflows:
      - worflow for dev
    types:
      - completed

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install

      - name: Run backend unit tests
        run: |
          cd backend
          npm test

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Run frontend unit tests
        run: |
          cd frontend
          npm test

      - name: Build Docker images
        run: docker-compose build

      - name: Tag Docker images for Docker Hub
        run: |
          docker tag backend your-dockerhub-username/backend:latest
          docker tag frontend your-dockerhub-username/frontend:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          docker push your-dockerhub-username/backend:latest
          docker push your-dockerhub-username/frontend:latest

      - name: Run end-to-end tests
        run: |
          docker-compose up -d
          docker-compose down
