name: CI/CD for main

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: 16
        working-directory: ./backend

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 16
        working-directory: ./frontend

      - name: Install dependencies for Backend
        run: npm install
        working-directory: ./backend

      - name: Install dependencies for Frontend
        run: npm install
        working-directory: ./frontend

      - name: Run Backend Unit Tests
        run: npm test
        working-directory: ./backend

      - name: Run Frontend Unit Tests
        run: npm test
        working-directory: ./frontend

      - name: Run E2E Tests
        run: npm run e2e
        working-directory: ./e2e-tests

      - name: Build Docker Images
        run: docker-compose build

      - name: Push Docker Images to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker-compose push
